var data = {
    "type":"dropdown",
    "questions":[
        {
            "markup":'<p>Researchers have documented many cases of the pollution limit being exceeded – in one <select class="btn btn-default"><option value="-1"></option><option value="0">instance</option><option value="1">hence</option></select> it was over ten times the legal safe level.<br><br>Many experts recommend engaging with the relevant <select class="btn btn-default"><option value="-1"></option><option value="0">professionally</option><option value="1">professionalism</option><option value="2">professional</option></select> bodies in your field of study while you are still at university.<br><br>Expressions of interest are sought from those wishing to attend the <select class="btn btn-default"><option value="-1"></option><option value="0">conferring</option><option value="1">conference</option><option value="2">confer</option></select>.<br><br>These organisations can be vital to people with severe physical disabilities, who often feel <select class="btn btn-default"><option value="-1"></option><option value="0">excluded</option><option value="1">attributed</option></select> from their community.</p>',
            "key":[0,2,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>It’s important to bear in mind that these <select class="btn btn-default"><option value="-1"></option><option value="0">statistics</option><option value="1">parameters</option></select> can only give us a general idea of the situation.<br><br>In order to <select class="btn btn-default"><option value="-1"></option><option value="0">specify</option><option value="1">ensure</option></select> that no contamination was possible, samples were stored under industry-standard conditions and kept secure at all times.<br><br>In fact, the setting of <select class="btn btn-default"><option value="-1"></option><option value="0">funds</option><option value="1">goals</option></select>, and a systematic approach in working towards them, can help reduce the amount of stress dramatically.<br><br>Research suggests that many young people experience anxiety when they are deprived of communication <select class="btn btn-default"><option value="-1"></option><option value="0">technological</option><option value="1">technology</option><option value="2">technologically</option></select> such as a mobile.</p></div>',
            "key":[0,1,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>Reacting against the <select class="btn btn-default"><option value="-1"></option><option value="0">sufficient</option><option value="1">dominant</option></select> social beliefs of the early 20th century, these women revolutionised the position of women in public life.<br><br>The Spencer Prize is an <select class="btn btn-default"><option value="-1"></option><option value="0">annual</option><option value="1">cycle</option></select> award given for excellence in collaborative research.<br><br>Whilst some continue to <select class="btn btn-default"><option value="-1"></option><option value="0">predict</option><option value="1">debate</option></select> the exact causes of the problem, there is a general move towards the acceptance of Grave’s Theory.<br><br>The committee’s role is to oversee the <select class="btn btn-default"><option value="-1"></option><option value="0">investigation</option><option value="1">investigate</option><option value="2">investigative</option></select> into the reasons for the decline.</p></div>',
            "key":[1,0,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>In order to better support <select class="btn btn-default"><option value="-1"></option><option value="0">communication</option><option value="1">proportion</option></select> across cultural barriers, training seminars in cultural awareness are highly recommended.<br><br>This opportunity is limited to a <select class="btn btn-default"><option value="-1"></option><option value="0">maximum</option><option value="1">principal</option></select> of fifteen students, so competition for places is expected to be fierce.<br><br>Millions of people around the world lack access to <select class="btn btn-default"><option value="-1"></option><option value="0">apparent</option><option value="1">adequate</option></select> shelter and drinking water.<br><br>Although the regulations were welcomed by many in the community, there were some who felt that the likely <select class="btn btn-default"><option value="-1"></option><option value="0">negate</option><option value="1">negatively</option><option value="2">negative</option></select> effects had been overlooked.</p></div>',
            "key":[0,0,1,2],
            "answered":false
        },
        {
            "markup":'<div><p>Of course, <select class="btn btn-default"><option value="-1"></option><option value="0">physical</option><option value="1">internal</option></select> activity becomes much more difficult for the elderly, particularly those with conditions of the bones or joints.<br><br>Students are expected to complete tasks in small groups, with a strong <select class="btn btn-default"><option value="-1"></option><option value="0">reaction</option><option value="1">emphasis</option></select> placed on the development of collaborative skills.<br><br>Many people who experience sleeplessness look for a more natural <select class="btn btn-default"><option value="-1"></option><option value="0">output</option><option value="1">alternative</option></select> to sleeping pills, such as lavender oil.<br><br>Although accidents may seem like random events, often they are in fact the result of a <select class="btn btn-default"><option value="-1"></option><option value="0">sequence</option><option value="1">shift</option></select> of smaller actions.</p></div>',
            "key":[0,1,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>All of the various <select class="btn btn-default"><option value="-1"></option><option value="0">components</option><option value="1">outcomes</option></select> of the machinery must be checked for faults every twelve months.<br><br>Over the last decade we have seen a marked increase in <select class="btn btn-default"><option value="-1"></option><option value="0">immigrate</option><option value="1">immigration</option><option value="2">immigrated</option></select> from Horn of Africa countries such as South Sudan, Somalia and Ethiopia.<br><br>It is essential to evaluate the <select class="btn btn-default"><option value="-1"></option><option value="0">concentration</option><option value="1">validity</option></select> of your research findings for different purposes such as decision making or trend analysis.<br><br>This is a complex issue, and <select class="btn btn-default"><option value="-1"></option><option value="0">considerable</option><option value="1">approximate</option></select> research is needed into the likely impact of a change of policy at this time.<br><br>Rather, developing countries often face <select class="btn btn-default"><option value="-1"></option><option value="0">constrained</option><option value="1">constrain</option><option value="2">constraints</option></select> such as lack of infrastructure, which make widespread health programs challenging.</p></div>',
            "key":[0,1,1,0,2],
            "answered":false
        },
        {
            "markup":'<div><p>It is essential to <select class="btn btn-default"><option value="-1"></option><option value="0">documentation</option><option value="1">document</option><option value="2">documenting</option></select> all safety incidents and accidents, however minor they may seem.<br><br>The community development <select class="btn btn-default"><option value="-1"></option><option value="0">deduction</option><option value="1">framework</option></select> provides support which enables both groups and individuals to better engage with their communities.<br><br>The courts <select class="btn btn-default"><option value="-1"></option><option value="0">imposed</option><option value="1">emerged</option></select> a sentence that many in the community felt did not reflect the severity of the crime.<br><br>Under the current political <select class="btn btn-default"><option value="-1"></option><option value="0">reliance</option><option value="1">regime</option></select>, it is unlikely that any significant changes will be made to taxation levels.<br><br>There can be no <select class="btn btn-default"><option value="-1"></option><option value="0">justification</option><option value="1">implementation</option></select> for intentional plagiarism, and the academic community does not tolerate it under any circumstance.</p></div>',
            "key":[1,1,0,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>The<select class="btn btn-default"><option value=-1><option value=0>mechanism<option value=1>philosophy</select>for transmitting these particles has yet to be fully understood.<br><br>Despite the huge geographical distances between them, there are many<select class="btn btn-default"><option value=-1><option value=0>paralleling<option value=1>unparalleled<option value=2>parallels</select>in the traditional stories of cultures from both Asia and Europe.<br><br>There is a clear<select class="btn btn-default"><option value=-1><option value=0>contrast<option value=1>contribution</select>between the two approaches, but both produce similar end results.<br><br>To<select class="btn btn-default"><option value=-1><option value=0>access<option value=1>illustrate</select>this point further, Figure 4.3 shows the likely results when age is taken into consideration.<br><br>Importantly, a decrease in crime levels does not necessarily lead to a<select class="btn btn-default"><option value=-1><option value=0>link<option value=1>corresponding</select>rise in the public’s perception of safety.</div>',
            "key":[0,2,0,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>The aim is to find a<select class="btn btn-default"><option value=-1><option value=0>resolution<option value=1>resolve<option value=2>resolved</select>that is acceptable and beneficial to both parties, thereby avoiding legal action.<br><br>It is likely that any change to the way education is funded will have far-reaching<select class="btn btn-default"><option value=-1><option value=0>implicate<option value=1>implicated<option value=2>implications</select>for the academic success of this entire generation.<br><br>The exceptionally heavy rainfall, and the<select class="btn btn-default"><option value=-1><option value=0>subsequent<option value=1>prior</select>widespread flooding, left the banana crops in ruin.<br><br>Students will be encouraged to explore a range of experimental<select class="btn btn-default"><option value=-1><option value=0>techniques<option value=1>circumstances</select>for working with materials such as wood, fabric and metal.<br><br>Innovative measures to ease the<select class="btn btn-default"><option value=-1><option value=0>task<option value=1>volume</select>of traffic entering the city during peak hours will be discussed.<br></div>',
            "key":[0,2,0,0,1],
            "answered":false
        }
    ]

}