var data = {
    "type":"dropdown",
    "questions":[
        {
            "markup":'<div><p>In a bid to find more <select class="btn btn-default"><option value="-1"></option><option value="0">sustainable</option><option value="1">underlying</option></select> types of engine fuel, the aviation industry is experimenting with the use of eucalypt trees in biofuel.</p><p>These measurements are <select class="btn btn-default"><option value="-1"></option><option value="0">capable</option><option value="1">accurate</option></select> to within one one-hundredth of a millimetre.</p><p>This paper sets out to <select class="btn btn-default"><option value="-1"></option><option value="0">draft</option><option value="1">challenge</option></select> the current accepted approach by proposing a new design framework.</p><p>The third <select class="btn btn-default"><option value="-1"></option><option value="0">edit</option><option value="1">edition</option><option value="2">editor</option></select> of the book contains a revised section on the use of technology to support research in the area.</p></div>',
            "key":[0,1,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>It is believed in some circles that William Shakespeare may not be the real <select class="btn btn-default"><option value="-1"></option><option value="0">authorship</option><option value="1">authored</option><option value="2">author</option></select> of his plays.</p><p>Experts anticipate that demand for land for new developments will far <select class="btn btn-default"><option value="-1"></option><option value="0">exceed</option><option value="1">bond</option></select> the availability of such land within the next fifty years.</p><p>Reports of the high <select class="btn btn-default"><option value="-1"></option><option value="0">incident</option><option value="1">incidence</option><option value="2">incidentally</option></select> of success with this procedure are encouraging.</p><p>This online delivery model provides more <select class="btn btn-default"><option value="-1"></option><option value="0">flexibility</option><option value="1">evolution</option></select> to how the individual accesses and interacts with the learning materials.</p></div>',
            "key":[2,0,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>Candidates will possess an <select class="btn btn-default"><option value="-1"></option><option value="0">orientation</option><option value="1">orientate</option><option value="2">orientating</option></select> to lifelong learning, demonstrated in their commitment to professional development.</p><p>Industry placements are an integral part of the course, and <select class="btn btn-default"><option value="-1"></option><option value="0">nevertheless</option><option value="1">furthermore</option></select> often provide the most valuable outcomes for students.</p><p>There is often <select class="btn btn-default"><option value="-1"></option><option value="0">conflicting</option><option value="1">conflict</option><option value="2">conflicted</option></select> between the desire to be environmentally-friendly and the financial cost of ‘green’ products such as organic food.</p><p>There is usually an <select class="btn btn-default"><option value="-1"></option><option value="0">conflict</option><option value="1">expansion</option></select> of around seven to eight years between the discovery of a vaccine and it being commercially available to the public.</p></div>',
            "key":[0,1,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>The recent upward <select class="btn btn-default"><option value="-1"></option><option value="0">clause</option><option value="1">trend</option></select> follows a period of relative instability in the market.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">modify</option><option value="1">modification</option><option value="2">modified</option></select> of the computer system will enhance our data handling capabilities.</p><p>Several data <select class="btn btn-default"><option value="-1"></option><option value="0">recovery</option><option value="1">expansion</option></select> measures can be implemented in the event of the loss of important information.</p><p>Applicants must have a high school certificate or <select class="btn btn-default"><option value="-1"></option><option value="0">version</option><option value="1">equivalent</option></select> qualification.</p></div>',
            "key":[1,1,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>It is important to be <select class="btn btn-default"><option value="-1"></option><option value="0">aware</option><option value="1">rational</option></select> of different cultural sensitivities when conducting business meetings with international clients.</p><p>Many see this announcement as merely a <select class="btn btn-default"><option value="-1"></option><option value="0">mental</option><option value="1">symbolic</option></select> gesture, since it appears there has been no real change to the policies of this government.</p><p>The submissions will be reviewed by a panel of both academic staff and <select class="btn btn-default"><option value="-1"></option><option value="0">externalise</option><option value="1">external</option><option value="2">externally</option></select> experts.</p><p>Occasionally, a person’s <select class="btn btn-default"><option value="-1"></option><option value="0">inhibition</option><option value="1">motivation</option></select> can be so powerful as to make them unable to engage in even the most simple of social interactions.</p></div>',
            "key":[0,1,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>In <select class="btn btn-default"><option value="-1"></option><option value="0">liberal</option><option value="1">liberalise</option><option value="2">liberalism</option></select> democratic societies, the role of the media in reporting on, criticising and to some extent shaping government policy is complex.</p><p>This paper aims to make an <select class="btn btn-default"><option value="-1"></option><option value="0">expert</option><option value="1">explicit</option></select> link between governmental policies of the last twenty years and the current rise in homelessness.</p><p>The 50+ age group reported that they used the Internet for 30 minutes a day, <select class="btn btn-default"><option value="-1"></option><option value="0">whereas</option><option value="1">nevertheless</option></select> those aged 18-30 spent almost five times as long surfing the Web.</p><p>The award is presented to the student with the best <select class="btn btn-default"><option value="-1"></option><option value="0">aggregate</option><option value="1">federal</option></select> performance in the final year of the program.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">perspective</option><option value="1">stability</option></select> of the compound at various temperatures was tested.</p></div>',
            "key":[0,1,0,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>I’ll first give a <select class="btn btn-default"><option value="-1"></option><option value="0">briefly</option><option value="1">brevity</option><option value="2">brief</option></select> overview of the background of the case, before looking in detail at how this particular corporation was able to overcome the problem.</p><p>The entire sector has operated at only <select class="btn btn-default"><option value="-1"></option><option value="0">marginal</option><option value="1">underlying</option></select> profits for several months, with many commentators predicting further decline.</p><p>Whilst a discussion of the long-term implications of the policy is of course necessary, such discussion lies outside the <select class="btn btn-default"><option value="-1"></option><option value="0">network</option><option value="1">scope</option></select> of this paper.</p><p>Because problem-solving tasks are <select class="btn btn-default"><option value="-1"></option><option value="0">cooperative</option><option value="1">precise</option></select> in nature, participants’ teamwork skills are enhanced.<br>&nbsp;<br>The <select class="btn btn-default"><option value="-1"></option><option value="0">diversity</option><option value="1">minimum</option></select> of plant life in this small area of rainforest is remarkable.<br>&nbsp;</p></div>',
            "key":[2,0,1,0,0],
            "answered":false
        },
        {
            "markup":'<div><p>In order to <select class="btn btn-default"><option value="-1"></option><option value="0">facilitate</option><option value="1">expose</option></select> the discussion, each group appointed a ‘leader’ who was asked to read a series of questions and record the responses.</p><p>It will be necessary to make an <select class="btn btn-default"><option value="-1"></option><option value="0">adjusted</option><option value="1">adjustment</option><option value="2">adjust</option></select> to the schedule, to allow for the late arrival of the delegates from Norway.</p><p>When we <select class="btn btn-default"><option value="-1"></option><option value="0">trace</option><option value="1">pursue</option></select> a particular line of reasoning, we must also be willing to acknowledge conflicting evidence, and allow that to inform our theory.</p><p>Participants in the first group were given the drug, and then asked to follow a series of simple <select class="btn btn-default"><option value="-1"></option><option value="0">initiatives</option><option value="1">instructions</option></select> designed to test their alertness.</p><p>Ultimately the findings were <select class="btn btn-default"><option value="-1"></option><option value="0">rejection</option><option value="1">reject</option><option value="2">rejected</option></select> as unreliable, given the conflicting reports of how the experiments had been conducted.</p></div>',
            "key":[0,1,1,1,2],
            "answered":false
        },
        {
            "markup":'<div><p>Because images can now be digitally <select class="btn btn-default"><option value="-1"></option><option value="0">enhancement</option><option value="1">enhanced</option><option value="2">enhancing</option></select>, young people are increasingly being exposed to unrealistic images of beauty.</p><p>The current focus on constructing carbon <select class="btn btn-default"><option value="-1"></option><option value="0">neutral</option><option value="1">rational</option></select> buildings is an indication of how influential the environmental message has become.</p><p>In general, the <select class="btn btn-default"><option value="-1"></option><option value="0">presumption</option><option value="1">allocation</option></select> is that the intellectual property of employees is in fact owned by their employers.</p><p>If it is not possible to access the materials locally, in some cases a <select class="btn btn-default"><option value="-1"></option><option value="0">substituted</option><option value="1">substituting</option><option value="2">substitution</option></select> can be made without detracting from the overall design.</p><p>In response to the committee’s proposals, Associate Professor Julia Karnik warned that the report largely <select class="btn btn-default"><option value="-1"></option><option value="0">ignoring</option><option value="1">ignored</option><option value="2">ignore</option></select> young people.</p></div>',
            "key":[1,0,0,2,1],
            "answered":false
        }
    ]

}