var data = {
    "type":"dropdown",
    "questions":[
        {
            "markup":'<div><p>To see how far people would obey orders, Milgram set up an experiment <select class="btn btn-default"><option value="-1"></option><option value="0">thereby</option><option value="1">whereby</option></select> participants were instructed to give electric shocks to others. &nbsp;</p><p>Finding participants for your research can be a major challenge, as people are often <select class="btn btn-default"><option value="-1"></option><option value="0">inclined</option><option value="1">reluctant</option></select> to give up their time without financial reward.</p><p>In fact, workers who were motivated by <select class="btn btn-default"><option value="-1"></option><option value="0">intrinsic</option><option value="1">incompatible</option></select> factors such as pride in their performance were much less likely to engage in bullying.</p><p>Any changes to regulations governing mandatory listing of ingredients in food labelling will <select class="btn btn-default"><option value="-1"></option><option value="0">likewise</option><option value="1">whereas</option></select> affect the cosmetics industry. &nbsp;</p><p>The government has imposed a flood <select class="btn btn-default"><option value="-1"></option><option value="0">panel</option><option value="1">levy</option></select>, a one-off tax to help meet the cost of rebuilding infrastructure after the recent natural disasters.</p></div>',
            "key":[1,1,0,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>Community workers often report that their attempts to advocate on <select class="btn btn-default"><option value="-1"></option><option value="0">encounter</option><option value="1">behalf</option></select> of their clients are frustrated by unnecessary bureaucracy.</p><p>The children who attended more than 5 hours of after-school classes per week had greater anxiety; <select class="btn btn-default"><option value="-1"></option><option value="0">nevertheless</option><option value="1">conversely</option></select>, their grades were not higher. &nbsp;</p><p>Participants were given a <select class="btn btn-default"><option value="-1"></option><option value="0">vision</option><option value="1">scenario</option></select> in which they were asked to decide which patient would receive a life-saving but expensive treatment.</p><p>Even the most robust economy is <select class="btn btn-default"><option value="-1"></option><option value="0">nonetheless</option><option value="1">forthcoming</option></select> vulnerable to the effects of a global recession.&nbsp; &nbsp;</p><p>The body has an <select class="btn btn-default"><option value="-1"></option><option value="0">inherent</option><option value="1">integral</option></select> ability to heal itself, but these processes can be interrupted by factors such as poor diet or substance abuse.</p></div>',
            "key":[1,1,1,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>In response to the H1N1 pandemic, many organisations developed a strict <select class="btn btn-default"><option value="-1"></option><option value="0">protocol</option><option value="1">route</option></select> to be followed in the event of an outbreak of the illness.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">coincidental</option><option value="1">qualitative</option></select> research involved interviewing groups of residents from three aged-care facilities on their experiences of isolation.</p><p>It is clear that, <select class="btn btn-default"><option value="-1"></option><option value="0">whereby</option><option value="1">notwithstanding</option></select> the recent efforts of the national broadcaster, there is still a lack of ethnic diversity on our TV screens.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">ongoing</option><option value="1">undergoing</option></select> debate on the effects of this policy is masking the real issue; the policy is in fact illegal and must be challenged in the courts.</p><p>Acceptance of these values is spreading, <select class="btn btn-default"><option value="-1"></option><option value="0">whereas</option><option value="1">albeit</option></select> slowly, mainly through a social networking campaign which recently achieved 100,000 followers.</p></div>',
            "key":[0,1,1,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>The work was <select class="btn btn-default"><option value="-1"></option><option value="0">conceived</option><option value="1">posed</option></select> and produced in collaboration with artists from the Ukraine, and explores notions of freedom and confinement.</p><p>The right to free speech is often <select class="btn btn-default"><option value="-1"></option><option value="0">invoked</option><option value="1">convinced</option></select> by some sections of the media as a justification for the publication of offensive material.</p><p>Parents can struggle with the <select class="btn btn-default"><option value="-1"></option><option value="0">furthermore</option><option value="1">so-called</option></select> ‘terrible twos’ – the stage of development at which a child often becomes uncooperative. &nbsp;</p><p>It is often suggested that the lives of humans and their interactions with the world are <select class="btn btn-default"><option value="-1"></option><option value="0">coincidental</option><option value="1">analogous</option></select> with actors playing roles on stage.</p><p>Research into aircraft structural <select class="btn btn-default"><option value="-1"></option><option value="0">devotion</option><option value="1">integrity</option></select> has resulted in huge advances in the safety and capabilities of modern planes.</p></div>',
            "key":[0,0,1,1,1],
            "answered":false
        }
    ]

}