var data = {
    "type":"dropdown",
    "questions":[
        {
            "markup":'<div><p>One major drawback was the <select class="btn btn-default"><option value="-1"></option><option value="0">manually</option><option value="1">manual</option><option value="2">manuals</option></select> operation of the pump, which dramatically reduced the output potential of the machine.</p><p>Quality <select class="btn btn-default"><option value="-1"></option><option value="0">assurance</option><option value="1">integrity</option></select> processes in the food industry are vital in order to comply with strict government health and safety regulations.</p><p>Particles of these pollutants are <select class="btn btn-default"><option value="-1"></option><option value="0">suspension</option><option value="1">suspends</option><option value="2">suspended</option></select> in the water, invisible to the naked eye, and therefore a great health hazard.</p><p>Despite the recent reports on the dangers of elective cosmetic surgery, it is not likely that this practice will <select class="btn btn-default"><option value="-1"></option><option value="0">cease</option><option value="1">ceaseless</option><option value="2">ceased</option></select> in the near future.</p></div>',
            "key":[1,0,2,0],
            "answered":false
        },
        {
            "markup":'<div><p>The software carries a <select class="btn btn-default"><option value="-1"></option><option value="0">concurrent</option><option value="1">adjacent</option></select> licence, meaning that it can be installed on all the organisation’s licensed computers at the same time.</p><p>The technology is designed to be <select class="btn btn-default"><option value="-1"></option><option value="0">invoked</option><option value="1">straightforward</option></select>, such that a person with only very limited experience in using a PC can quickly master it.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">sphere</option><option value="1">bulk</option></select> of the funding comes from corporate sponsorship, which, critics say, shows that the government is neglecting its responsibility to the Arts.</p><p>Despite worldwide outcry at the apparent <select class="btn btn-default"><option value="-1"></option><option value="0">violated</option><option value="1">violation</option><option value="2">violate</option></select> of human rights within the notorious Guantanamo Bay prison, it was not closed until 2009.</p></div>',
            "key":[0,1,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>One of the most common complaints about this technology is that it is <select class="btn btn-default"><option value="-1"></option><option value="0">incompatible</option><option value="1">reluctant</option></select> with many web applications such as video streaming.</p><p>Communities have always needed faith, myth or ritual to ensure <select class="btn btn-default"><option value="-1"></option><option value="0">format</option><option value="1">coherence</option></select> is maintained.</p><p>“Professor Mitchell is here tonight to give us his <select class="btn btn-default"><option value="-1"></option><option value="0">norms</option><option value="1">insights</option></select> into the tension between the need for border security and the plight of refugees.”</p><p>It has become common for leaders during a recession to <select class="btn btn-default"><option value="-1"></option><option value="0">restraint</option><option value="1">restrain</option><option value="2">restraining</option></select> wage increases for politicians as a symbol of solidarity with the people.<br>&nbsp;</p></div>',
            "key":[0,1,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>Although the wood is treated and stained in Europe, <select class="btn btn-default"><option value="-1"></option><option value="0">maturity</option><option value="1">assembly</option></select> of the furniture actually takes place in a manufacturing plant in China.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">medium</option><option value="1">minimal</option></select> requirements for life are food, water and shelter, yet much of the world’s population struggles to secure even these basic needs.</p><p>It is not uncommon for patients to suffer a <select class="btn btn-default"><option value="-1"></option><option value="0">temporary</option><option value="1">supplementary</option></select> relapse after receiving the treatment, but recovery is usually swift.</p><p>We <select class="btn btn-default"><option value="-1"></option><option value="0">anticipating</option><option value="1">anticipation</option><option value="2">anticipate</option></select> that the first phase of trialling will reveal no adverse side effects, and therefore the clinical trials will be approved.</p></div>',
            "key":[1,1,0,2],
            "answered":false
        },
        {
            "markup":'<div><p><select class="btn btn-default"><option value="-1"></option><option value="0">Preliminary</option><option value="1">Notwithstanding</option></select> results from the research suggest that perceived pressure to look good is a significant factor in pregnant women’s food choices.</p><p>One such breakthrough was the development of a <select class="btn btn-default"><option value="-1"></option><option value="0">scenario</option><option value="1">device</option></select> which allowed a sample of the blood to be instantly analysed for multiple allergies.</p><p>A smell can <select class="btn btn-default"><option value="-1"></option><option value="0">triggering</option><option value="1">trigger</option><option value="2">triggered</option></select> a memory of a specific place or event, but could smells be used to aid memory recall of items such as numbers or facts?</p><p>Any period of instability tends to be of relatively short <select class="btn btn-default"><option value="-1"></option><option value="0">vision</option><option value="1">duration</option></select>, as the ruling power will work swiftly and decisively to restore control.</p></div>',
            "key":[0,1,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>In family businesses, the <select class="btn btn-default"><option value="-1"></option><option value="0">overlap</option><option value="1">protocol</option></select> of usually separate relationships can cause tension; for example father-son can also be boss-employee.</p><p>Meditation is increasingly being utilised by professionals in all fields as a way to <select class="btn btn-default"><option value="-1"></option><option value="0">conceive</option><option value="1">attain</option></select> the calm and focus necessary for peak performance.</p><p>Work has <select class="btn btn-default"><option value="-1"></option><option value="0">founded</option><option value="1">commenced</option></select> on the main stadium complex, which will take five years, and a team of 420, to construct.</p><p>Sustainability is an <select class="btn btn-default"><option value="-1"></option><option value="0">integral</option><option value="1">intermediate</option></select> part of the design, and materials have been chosen for their minimal impact on the environment.</p><p>Ultimately, the funding body must be <select class="btn btn-default"><option value="-1"></option><option value="0">convinced</option><option value="1">invoked</option></select> that your research will produce findings that can be applied in the real world.</p></div>',
            "key":[0,1,1,0,0],
            "answered":false
        },
        {
            "markup":'<div><p>The defence of <select class="btn btn-default"><option value="-1"></option><option value="0">subordinate</option><option value="1">diminished</option></select> responsibility argues that due to a mental impairment, the accused should not be held responsible for their crime.</p><p>It will almost certainly be necessary to <select class="btn btn-default"><option value="-1"></option><option value="0">relax</option><option value="1">refine</option></select> your original question once the preliminary reading for your essay is completed.</p><p>What critics call the <select class="btn btn-default"><option value="-1"></option><option value="0">erosion</option><option value="1">depression</option></select> of standards of grammar and spelling is, in fact, just the development of language to fit new social contexts.</p><p>The new regulations will bring with them increased penalties <select class="btn btn-default"><option value="-1"></option><option value="0">whereby</option><option value="1">albeit</option></select> any organisation in breach of the rules will face a fine of $300,000.</p><p>Food is <select class="btn btn-default"><option value="-1"></option><option value="0">supplementary</option><option value="1">intrinsic</option></select> to the country\'s culture, with family mealtimes being especially important.</p></div>',
            "key":[1,1,0,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>Occasionally it is not possible to resolve the dispute internally, in which case external <select class="btn btn-default"><option value="-1"></option><option value="0">mediation</option><option value="1">controversy</option></select> can be productive.</p><p>There has been some recent speculation on the possibility of a <select class="btn btn-default"><option value="-1"></option><option value="0">unified</option><option value="1">compiled</option></select> Asian currency, but the Euro’s problems suggest this may be unwise.</p><p>For instance, families who provide <select class="btn btn-default"><option value="-1"></option><option value="0">passive</option><option value="1">ongoing</option></select> care for elderly relatives would undoubtedly benefit from this kind of financial assistance.</p><p>Learning is not <select class="btn btn-default"><option value="-1"></option><option value="0">confining</option><option value="1">confined</option><option value="2">confines</option></select> to the classroom, nor is it solely managed by teachers; students must drive how they engage with the material.</p><p>The tension between humans and their environment, whether natural or man-made, is a <select class="btn btn-default"><option value="-1"></option><option value="0">devoted</option><option value="1">persistent</option></select> theme of her films.</p></div>',
            "key":[0,0,1,1,1],
            "answered":false
        },
        {
            "markup":'<div><p>The digital <select class="btn btn-default"><option value="-1"></option><option value="0">revolution</option><option value="1">levy</option></select> has affected every aspect of the media, from the way it is produced and received to how the audience interacts with it.</p><p>Statistics can easily be <select class="btn btn-default"><option value="-1"></option><option value="0">distortion</option><option value="1">distorted</option><option value="2">distorting</option></select> or manipulated, so it’s important to understand who carried out the research, and how it was funded.</p><p>The collaboration is of <select class="btn btn-default"><option value="-1"></option><option value="0">likewise</option><option value="1">mutual</option></select> benefit; the trainees learn from the experience of the professionals but also contribute a fresh perspective.</p><p>It is intriguing to consider what the implications of a <select class="btn btn-default"><option value="-1"></option><option value="0">collapsible</option><option value="1">collapsed</option><option value="2">collapse</option></select> of the Internet might be, given how central it has become in our lives.</p><p>A research proposal must address any <select class="btn btn-default"><option value="-1"></option><option value="0">ethical</option><option value="1">ethics</option><option value="2">ethical</option></select> issues related to the research before it can be approved.<br>&nbsp;</p></div>',
            "key":[0,1,1,2,0],
            "answered":false
        }
    ]

}