var data = {
    "type":"dropdown",
    "questions":[
        {
            "markup":'<div><p>The recent <select class="btn btn-default"><option value="-1"></option><option value="0">dramatic</option><option value="1">definite</option></select> economic decline of several countries in the European Union has sparked debate about the future of the Euro.<p></p>By studying clothing and tools found at archaeological sites, researchers have <select class="btn btn-default"><option value="-1"></option><option value="0">inferred</option><option value="1">converted</option></select> much about the lifestyle of humans many centuries ago.<p></p>The most interesting results came from questions 15-19, (see <select class="btn btn-default"><option value="-1"></option><option value="0">channel</option><option value="1">appendix</option></select> 3 for the complete questionnaire).<p></p>A new street level drainage system has been designed, <select class="btn btn-default"><option value="-1"></option><option value="0">minimise</option><option value="1">minimising</option><option value="2">minimised</option></select> the potential for flooding during the annual monsoonal rains.<p></p>During the <select class="btn btn-default"><option value="-1"></option><option value="0">simulate</option><option value="1">simulator</option><option value="2">simulation</option></select>, nursing students experienced a typical night in a hospital emergency ward, with actors playing the patients.</p></div>',
            "key":[0,0,1,1,2],
            "answered":false
        },
        {
            "markup":'<div><p>Despite undoubted differences between <select class="btn btn-default"><option value="-1"></option><option value="0">classics</option><option value="1">classic</option><option value="2">classical</option></select> and modern approaches to research in this area, there is a common purpose evident in both.<p></p>Some argue that the <select class="btn btn-default"><option value="-1"></option><option value="0">exploitation</option><option value="1">exploits</option><option value="2">exploited</option></select> of the rich mineral resources in the area, while economically beneficial, is environmentally disastrous.<p></p>This semester, a series of guest lectures by distinguished visiting industry experts will <select class="btn btn-default"><option value="-1"></option><option value="0">complementary</option><option value="1">complement</option><option value="2">complemented</option></select> the learning experiences in the tutorials.<p></p>For the IT graduate, maintaining <select class="btn btn-default"><option value="-1"></option><option value="0">currency</option><option value="1">priority</option></select> of skills and knowledge is vital, as the technology and the theories are rapidly evolving.<p></p>There is a strong rural/urban <select class="btn btn-default"><option value="-1"></option><option value="0">differentiation</option><option value="1">accumulation</option></select> in the findings on ownership of household computers and household internet access.</p></div>',
            "key":[2,0,1,0,0],
            "answered":false
        },
        {
            "markup":'<div><p>The campaign to <select class="btn btn-default"><option value="-1"></option><option value="0">prohibited</option><option value="1">prohibit</option><option value="2">prohibitive</option></select> smoking in public places has so far not gained much support in many countries in Asia.<p></p>Although the <select class="btn btn-default"><option value="-1"></option><option value="0">identical</option><option value="1">empirical</option></select> research did not pinpoint any one pattern of behaviour in the adolescent male group, it did reveal some interesting data.<p></p>The <select class="btn btn-default"><option value="-1"></option><option value="0">foundation</option><option value="1">infrastructure</option></select> of all good academic writing is planning; without this, the writer’s ideas and arguments will not be expressed clearly.<p></p>One cannot <select class="btn btn-default"><option value="-1"></option><option value="0">deny</option><option value="1">deniable</option><option value="2">denial</option></select> the remarkable influence of Brown on the theories of the last fifty years, though many researchers now dismiss her approach.<p></p>Working within a <select class="btn btn-default"><option value="-1"></option><option value="0">widespread</option><option value="1">hierarchical</option></select> organisation can pose challenges for those not used to clearly marked lines of reporting and communication.<br>&nbsp;</p></div>',
            "key":[1,1,0,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>An abstract of 150-200 words must <select class="btn btn-default"><option value="-1"></option><option value="0">accompanied</option><option value="1">accompaniment</option><option value="2">accompany</option></select> any article submitted to the publication.<p></p>Because of <select class="btn btn-default"><option value="-1"></option><option value="0">innovative</option><option value="1">innovation</option><option value="2">innovate</option></select> in sports technology, sporting success can be determined not by the performance of the individual, but of their equipment.<p></p>Therefore, communities with greater <select class="btn btn-default"><option value="-1"></option><option value="0">adapt</option><option value="1">adaptability</option><option value="2">adaptation</option></select> abilities are significantly more likely to survive any economic difficulties resulting from climate change.<p></p>The aim is to examine <select class="btn btn-default"><option value="-1"></option><option value="0">contemporary</option><option value="1">arbitrary</option></select> issues in management, in order to better understand the constraints and challenges facing today’s managers.<p></p>The largest proportion of customers responded that they were only ‘<select class="btn btn-default"><option value="-1"></option><option value="0">somewhat</option><option value="1">inevitably</option></select> satisfied’ with the service provided.</p></div>',
            "key":[2,1,2,0,0],
            "answered":false
        },
        {
            "markup":'<div><p>This new policy regarding complaints seems <select class="btn btn-default"><option value="-1"></option><option value="0">ambiguous</option><option value="1">unique</option></select>, as it is not clear who has final responsibility for resolving the issue.<p></p>Participants for the study were sought on a <select class="btn btn-default"><option value="-1"></option><option value="0">crucial</option><option value="1">voluntary</option></select> basis, although the chance to win an iTunes gift voucher was offered as an incentive.<p></p>There seems to be a fundamental <select class="btn btn-default"><option value="-1"></option><option value="0">contradiction</option><option value="1">displacement</option></select> in a political ideology which promotes growth while at the same time encouraging tradition.<p></p>There are many possible interpretations of the film, but <select class="btn btn-default"><option value="-1"></option><option value="0">ultimately</option><option value="1">solely</option></select> its meaning will be determined by the individual experience of the viewer.<p></p>Both static and <select class="btn btn-default"><option value="-1"></option><option value="0">dynamics</option><option value="1">dynamic</option><option value="2">dynamically</option></select> testing of the structure and materials must be carried out to ensure peak performance.</p></div>',
            "key":[0,1,0,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>This lecture will <select class="btn btn-default"><option value="-1"></option><option value="0">highlight</option><option value="1">denote</option></select> the importance of childhood immunisation programs for successful eradication of disease.<p></p>Any participant who tested positive during the allergy test was <select class="btn btn-default"><option value="-1"></option><option value="0">automated</option><option value="1">automatically</option><option value="2">automatic</option></select> allocated to one of the trial groups for further treatment.<p></p><select class="btn btn-default"><option value="-1"></option><option value="0">Induced</option><option value="1">Implicit</option></select> in the use of computer-based learning in our universities is the expectation that all students are competent with this technology.<p></p>The software is designed to <select class="btn btn-default"><option value="-1"></option><option value="0">restore</option><option value="1">restoration</option><option value="2">restored</option></select> the most recent settings if a fault causes it to close unexpectedly.<p></p>They observed that the frogs with the greatest <select class="btn btn-default"><option value="-1"></option><option value="0">deviate</option><option value="1">deviated</option><option value="2">deviation</option></select> from the normal skin colour were the ones most likely to survive in the new habitat.</p></div>',
            "key":[0,1,1,0,2],
            "answered":false
        },
        {
            "markup":'<div><p>Recent studies have <select class="btn btn-default"><option value="-1"></option><option value="0">predominantly</option><option value="1">eventually</option></select> focussed on the genetic causes of the illness, but our intention is to investigate environmental factors.<p></p>We suggest that a <select class="btn btn-default"><option value="-1"></option><option value="0">isolated</option><option value="1">comprehensive</option></select> training and education program be introduced as a matter of urgency to avoid future incidents of this nature.<p></p>Although airline passengers are encouraged to believe that the baggage checks are <select class="btn btn-default"><option value="-1"></option><option value="0">random</option><option value="1">biased</option></select> in fact there is a clear pattern to the checks.<p></p>The goods must be packed into <select class="btn btn-default"><option value="-1"></option><option value="0">uniformly</option><option value="1">uniform</option><option value="2">uniformity</option></select> crates for shipment, in order to maximise the use of space and reduce handling charges.<p></p>The <select class="btn btn-default"><option value="-1"></option><option value="0">publication</option><option value="1">equipment</option></select> will focus largely on new developments in theory and practice in the field of traditional medicine.</p></div>',
            "key":[0,1,0,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>The organisation may <select class="btn btn-default"><option value="-1"></option><option value="0">terminal</option><option value="1">termination</option><option value="2">terminate</option></select> a partnership if a review reveals that the partner is failing to adhere to the conditions of the contract.<p></p>The desperate need for a massive increase in funding for public transport has been ignored by <select class="btn btn-default"><option value="-1"></option><option value="0">succession</option><option value="1">successive</option><option value="2">successor</option></select> governments.<p></p>The study of children with reading difficulties found that early <select class="btn btn-default"><option value="-1"></option><option value="0">intervention</option><option value="1">manipulation</option></select> resulted in greater improvement in the child’s reading ability.<p></p>Our supply of oil is <select class="btn btn-default"><option value="-1"></option><option value="0">finite</option><option value="1">radical</option></select> but our expanding population is not; how, therefore, will we ensure adequate fuel supplies in the future?<p></p>Although it often seems that <select class="btn btn-default"><option value="-1"></option><option value="0">thereby</option><option value="1">virtually</option></select> everyone owns a car, in fact there has been a recent sharp increase in the number of carless families.<br>&nbsp;</p></div>',
            "key":[2,1,0,0,1],
            "answered":false
        }
    ]

}