var data = {
    "type":"dropdown",
    "questions":[
        {
            "markup":'<div><p>Ensure the evidence was <select class="btn btn-default"  ><option value="-1"></option><option value="0">obtaining</option><option value="1">obtains</option><option value="2">obtained</option></select> lawfully, as any suspected failure to follow regulations may endanger the prosecution’s case.</p><p>Of the many <select class="btn btn-default" ><option value="-1"></option><option value="0">issues</option><option value="1">aspects</option></select> facing young people today, the social pressure to conform to a ‘perfect’ body type is among the most difficult.</p><p>How much a child allows peer pressure to <select class="btn btn-default" ><option value="-1"></option><option value="0">transfer</option><option value="1">affect</option></select> his or her decision-making process depends largely on family background and education.</p><p>The <select class="btn btn-default" ><option value="-1"></option><option value="0">conceptual</option><option value="1">concept</option><option value="2">conceptualise</option></select> for the project was conceived during the riots, as a response to prevailing attitudes towards those involved in the unrest.</p><p>It is anticipated that the results will be <select class="btn btn-default" ><option value="-1"></option><option value="0">consistent</option><option value="1">restricted</option></select> with Langham (2007), indicating a cyclical pattern of behaviour in this species.</p></div>',
            "key":[2,0,1,1,0],
            "answered":false
        },
        {
            "markup":'<div><p>The study will collate <select class="btn btn-default"  ><option value="-1"></option><option value="0">data</option><option value="1">percent</option></select> about average waiting times in the hospital system.</p><p>Schafer (2009) claims that White’s <select class="btn btn-default" ><option value="-1"></option><option value="0">definition</option><option value="1">interpretation</option></select> of the study was flawed because it failed to take into account the limited sample size.</p><p>The level of compensation payments to farmers will be <select class="btn btn-default" ><option value="-1"></option><option value="0">purchased</option><option value="1">derived</option></select> from the value of the land and its productivity over the previous two decades.</p><p>The study looked at one hundred aviation incidents in which human <select class="btn btn-default" ><option value="-1"></option><option value="0">factors</option><option value="1">consequences</option></select> were determined to be the main cause.</p><p>One goal of Human Resources theory and practice has been to improve an organisation’s ability to define the <select class="btn btn-default" ><option value="-1"></option><option value="0">regulations</option><option value="1">roles</option></select> of its employees.</p></div>',
            "key":[0,1,1,0,1],
            "answered":false
        },
        {
            "markup":'<div><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">functioning</option><option value="1">function</option><option value="2">functional</option></select> of the control group is to provide an untreated sample that the treatment group can be compared against.</p><p>The alumni association is a <select class="btn btn-default"><option value="-1"></option><option value="0">community</option><option value="1">distribution</option></select> of graduates who support each other through professional opportunities and social networking.</p><p>The results of the survey <select class="btn btn-default"><option value="-1"></option><option value="0">approach</option><option value="1">indicate</option></select> that any changes to policy at this stage are likely to be deeply unpopular with the majority of the public.</p><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">region</option><option value="1">regional</option><option value="2">regionally</option></select> is still recovering from the devastating effects of the earthquake and the consequent permanent relocation of many industries.</p><p>The belief that Columbus’ voyages introduced the <select class="btn btn-default"><option value="-1"></option><option value="0">theorist</option><option value="1">theoretical</option><option value="2">theory</option></select> of a spherical Earth is a misconception; it had already been accepted for centuries.</p></div>',
            "key":[1,0,1,0,2],
            "answered":false
        },
        {
            "markup":'<div><p>The <select class="btn btn-default"><option value="-1"></option><option value="0">majority</option><option value="1">majorities</option><option value="2">major</option></select> obstacle to a change of policy is the belief that companies should be free to set executive pay levels.</p><p>Understanding the <select class="btn btn-default"><option value="-1"></option><option value="0">potential</option><option value="1">available</option></select> pitfalls of the restaurant industry and how to avoid them will help to ensure your venture’s success.</p><p>The text “Aspects of War: representations of conflict in contemporary American cinema” is <select class="btn btn-default"><option value="-1"></option><option value="0">requiring</option><option value="1">required</option><option value="2">requirement</option></select> reading for this course.</p><p>The first stage of the plan is to <select class="btn btn-default"><option value="-1"></option><option value="0">estimation</option><option value="1">estimate</option><option value="2">estimated</option></select> the likely flood peak, using the available water catchment figures.</p><p>Many physicists <select class="btn btn-default"><option value="-1"></option><option value="0">sought</option><option value="1">occurred</option></select> to explain the atom, but it was Bohr’s concept of electrons that paved the way for quantum physics as we know it today.</p></div>',
            "key":[2,0,1,1,0],
            "answered":false
        },
        {
            "markup":'<div ><p>Participants were chosen through a selection <select class="btn btn-default"><option value="-1"></option><option value="0">processing</option><option value="1">process</option><option value="2">processed</option></select> which included taking a detailed medical history and a series of diagnostic tests.</p><p>The data was analysed by the <select class="btn btn-default"><option value="-1"></option><option value="0">variables</option><option value="1">methods</option></select> of gender and socio-economic status, and correlations between these and religious views were sought.</p><p>In daily life we take any number of ‘leaps of faith’ – we <select class="btn btn-default"><option value="-1"></option><option value="0">select</option><option value="1">assume</option></select> that the other drivers on the road will obey the rules, for example.</p><p>The STRIDE model, developed by Microsoft, identifies six <select class="btn btn-default"><option value="-1"></option><option value="0">categories</option><option value="1">categorising</option><option value="2">categorises</option></select> of threat to computer security.</p><p>It is often stated that at an <select class="btn btn-default"><option value="-1"></option><option value="0">individuality</option><option value="1">individualism</option><option value="2">individual</option></select> level, we can have little impact on climate change; we unconditionally refute that claim.</p></div>',
            "key":[1,0,1,0,2],
            "answered":false
        },
        {
            "markup":'<div ><p>Viewed in the <select class="btn btn-default"><option value="-1"></option><option value="0">contextualise</option><option value="1">contextual</option><option value="2">context</option></select> of the anxiety of post-WW2 Europe, it is easy to see why authorities decided the film was too frightening for audiences.</p><p>The potential risk of an investment can be <select class="btn btn-default"<option value="-1"></option><option value="0">evaluated</option><option value="1">evaluation</option><option value="2">evaluating</option></select> using several methods.</p><p>The project is a <select class="btn btn-default"><option value="-1"></option><option value="0">formula</option><option value="1">response</option></select> to Dunbar’s number, the theory that there are a finite number of meaningful relationships that a person can maintain.</p><p>The most impressive of the new technology’s <select class="btn btn-default"><option value="-1"></option><option value="0">features</option><option value="1">credits</option></select> is its ability to allow real-time audience interaction with a live broadcast.</p><p>This course focuses not only on the theory of urban design, but also on students’ <select class="btn btn-default"><option value="-1"></option><option value="0">acquiring</option><option value="1">acquisition</option><option value="2">acquires</option></select> of practical skills in CAD and project management.</p></div>',
            "key":[2,0,1,0,1],
            "answered":false
        },
        {
            "markup":'<div ><p>The environment created by casinos is designed to induce gamblers to become so <select class="btn btn-default"><option value="-1"></option><option value="0">involved</option><option value="1">structured</option></select> in their play that they lose track of time.</p><p>The Australian Capital Territory introduced this <select class="btn btn-default"><option value="-1"></option><option value="0">legislator</option><option value="1">legislation</option><option value="2">legislate</option></select> in 2006, but it was overturned by the federal government.</p><p>The society was <select class="btn btn-default"><option value="-1"></option><option value="0">designed</option><option value="1">established</option></select> in 1846 in order to promote the anthropological study of the many communities in the Islands.</p><p>Members of Generation Y may rightly feel aggrieved that they are often <select class="btn btn-default"><option value="-1"></option><option value="0">perceived</option><option value="1">perception</option><option value="2">perceiving</option></select> to be lazy, selfish and impatient.</p><p>The way in which companies <select class="btn btn-default"><option value="-1"></option><option value="0">assist</option><option value="1">conduct</option></select> job interviews has undergone many changes, particularly with the increased use of psychometric testing of candidates.</p></div>',
            "key":[0,1,1,0,1],
            "answered":false
        },
        {
            "markup":'<div ><p>Although these issues can be related to all levels of education, they are especially <select class="btn btn-default"><option value="-1"></option><option value="0">resident</option><option value="1">relevant</option></select> to primary education.</p><p>The strong dollar is increasing the difficulties for the retail <select class="btn btn-default"><option value="-1"></option><option value="0">sector</option><option value="1">chapter</option></select>, as shoppers move towards purchasing online from overseas retailers.</p><p>Managing the project is a <select class="btn btn-default"><option value="-1"></option><option value="0">complex</option><option value="1">beneficial</option></select> task, as it spans multiple disciplines and involves participants from three continents.</p><p>While the <select class="btn btn-default"><option value="-1"></option><option value="0">normal</option><option value="1">primary</option></select> goal of care at the facility is physical recovery after illness, patients also benefit mentally from each other’s support.</p><p>The Census, a <select class="btn btn-default"><option value="-1"></option><option value="0">surveying</option><option value="1">survey</option><option value="2">surveyed</option></select> of all households in the country, aims to provide important statistical information about population and lifestyle.</p></div>',
            "key":[1,0,0,1,1],
            "answered":false
        }
    ]

}